# This is a basic workflow to help you get started with Actions

name: matrix job workflow

# Controls when the workflow will run
on:
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
    matrix:
     os: 
      - ubuntu-latest
      - windows-latest
     java-version: [17,21]
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
      java-version: ${{matrix.java-version}}
      distribution: microsoft
