name: Parallel multiple tasks execution

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Task 1
        run: echo "Running Task 1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Task 2
        run: echo "Running Task 2"
